# Generated by Django 2.2.6 on 2020-06-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('todos_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Приоритет',
                'verbose_name_plural': 'Приоритеты',
            },
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='priority',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.ManyToManyField(blank=True, default='2', to='tasks.Priority'),
        ),
    ]
